name: SpigotPlugin
version: ${project.version}
main: dev.lightdream.slots.Main
authors: [ L1ghtDream ]
website: https://lightdream.dev
softdepend:
  - LightDreamAPI
commands:
  st:
    description: NA
  ld-api:
    description: NA